"""Example 1: Basic Routes

This example demonstrates creating basic GET and POST routes
with path parameters and query parameters.
"""

from fastapi import FastAPI, Query, Path
from fastapi.testclient import TestClient

# Create FastAPI application
app = FastAPI(
    title="Basic Routes Example",
    description="Demonstrates basic FastAPI routing",
    version="1.0.0",
)


# Simple GET endpoint
@app.get("/")
def read_root():
    """Return a welcome message."""
    return {"message": "Hello, FastAPI!"}


# GET with path parameter
@app.get("/items/{item_id}")
def read_item(
    item_id: int = Path(..., title="Item ID", description="The ID of the item to retrieve", ge=1),
):
    """Get an item by ID.

    The item_id is automatically validated as a positive integer.
    """
    return {"item_id": item_id, "name": f"Item {item_id}"}


# GET with query parameters
@app.get("/items/")
def list_items(
    skip: int = Query(0, ge=0, description="Number of items to skip"),
    limit: int = Query(10, ge=1, le=100, description="Maximum items to return"),
    search: str | None = Query(None, min_length=1, description="Search query"),
):
    """List items with pagination and optional search.

    - **skip**: Number of items to skip (default: 0)
    - **limit**: Maximum items to return (default: 10, max: 100)
    - **search**: Optional search query
    """
    items = [{"id": i, "name": f"Item {i}"} for i in range(skip, skip + limit)]

    if search:
        items = [item for item in items if search.lower() in item["name"].lower()]

    return {
        "items": items,
        "skip": skip,
        "limit": limit,
        "search": search,
    }


# Multiple path parameters
@app.get("/users/{user_id}/items/{item_id}")
def get_user_item(
    user_id: int = Path(..., description="The user ID"),
    item_id: int = Path(..., description="The item ID"),
    details: bool = Query(False, description="Include item details"),
):
    """Get a specific item belonging to a user."""
    result = {
        "user_id": user_id,
        "item_id": item_id,
    }
    if details:
        result["details"] = {
            "description": f"Detailed info for item {item_id}",
            "owner": f"User {user_id}",
        }
    return result


# POST endpoint with query parameters
@app.post("/items/")
def create_item(
    name: str = Query(..., min_length=1, max_length=100),
    price: float = Query(..., gt=0),
    description: str | None = Query(None, max_length=500),
):
    """Create a new item (using query parameters for simplicity).

    In real applications, use request body models (see example_2).
    """
    return {
        "id": 1,  # Would be generated by database
        "name": name,
        "price": price,
        "description": description,
    }


# Health check endpoint
@app.get("/health")
def health_check():
    """Health check endpoint for monitoring."""
    return {"status": "healthy"}


def demonstrate_routes():
    """Demonstrate the routes using TestClient."""
    print("Example 1: Basic Routes")
    print("=" * 50)

    client = TestClient(app)

    # 1. Root endpoint
    print("\n1. GET / - Root endpoint:")
    response = client.get("/")
    print(f"   Status: {response.status_code}")
    print(f"   Response: {response.json()}")

    # 2. Path parameter
    print("\n2. GET /items/{item_id} - Path parameter:")
    response = client.get("/items/42")
    print(f"   Status: {response.status_code}")
    print(f"   Response: {response.json()}")

    # 3. Invalid path parameter
    print("\n3. GET /items/invalid - Invalid path parameter:")
    response = client.get("/items/invalid")
    print(f"   Status: {response.status_code}")
    print(f"   Response: {response.json()}")

    # 4. Query parameters
    print("\n4. GET /items/ - Query parameters:")
    response = client.get("/items/?skip=5&limit=3")
    print(f"   Status: {response.status_code}")
    print(f"   Response: {response.json()}")

    # 5. Query parameter with search
    print("\n5. GET /items/ - With search:")
    response = client.get("/items/?search=item")
    print(f"   Status: {response.status_code}")
    print(f"   Items found: {len(response.json()['items'])}")

    # 6. Multiple path parameters
    print("\n6. GET /users/{user_id}/items/{item_id}:")
    response = client.get("/users/10/items/5?details=true")
    print(f"   Status: {response.status_code}")
    print(f"   Response: {response.json()}")

    # 7. POST with query parameters
    print("\n7. POST /items/ - Create item:")
    response = client.post("/items/?name=Widget&price=9.99&description=A useful widget")
    print(f"   Status: {response.status_code}")
    print(f"   Response: {response.json()}")

    # 8. POST with invalid price
    print("\n8. POST /items/ - Invalid price (negative):")
    response = client.post("/items/?name=Widget&price=-5")
    print(f"   Status: {response.status_code}")
    print(f"   Error: {response.json()['detail'][0]['msg']}")

    # 9. Health check
    print("\n9. GET /health - Health check:")
    response = client.get("/health")
    print(f"   Status: {response.status_code}")
    print(f"   Response: {response.json()}")

    # 10. OpenAPI docs available
    print("\n10. API Documentation:")
    print("    - Swagger UI: http://localhost:8000/docs")
    print("    - ReDoc: http://localhost:8000/redoc")
    print("    - OpenAPI JSON: http://localhost:8000/openapi.json")

    print("\nExample completed successfully!")


def main():
    """Run the example demonstration."""
    demonstrate_routes()


if __name__ == "__main__":
    main()
