# Configuration for Exercise 2
run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    shadow: true
