# SOLUTION 2: Optimized CI with Caching and Artifacts

name: CI (Optimized)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Built-in pip caching

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build application
        run: |
          mkdir -p dist
          cp -r app dist/
          echo "Build completed at $(date)" > dist/BUILD_INFO

      # Upload build artifacts for test job
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
          retention-days: 7

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Same cache as build job

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Download build artifacts from build job
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist/

      - name: Verify build
        run: |
          echo "Build info:"
          cat dist/BUILD_INFO

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          pytest --junitxml=test-results.xml --cov=app --cov-report=xml

      # Upload test results artifact
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if tests fail
        with:
          name: test-results
          path: |
            test-results.xml
            coverage.xml
          retention-days: 30

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Uses same cache key pattern

      # Cache ruff separately (faster than pip install every time)
      - name: Cache ruff
        uses: actions/cache@v4
        with:
          path: ~/.cache/ruff
          key: ruff-${{ runner.os }}

      - name: Install linter
        run: pip install ruff

      - name: Run lint
        run: ruff check app/
