# EXERCISE 2: Optimize this workflow with caching and artifacts
# Currently runs slowly without caching

name: CI (Slow)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          # TODO: Add pip caching

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build application
        run: |
          mkdir -p dist
          cp -r app dist/
          echo "Build completed at $(date)" > dist/BUILD_INFO

      # TODO: Upload build artifacts for test job

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          # TODO: Add pip caching (same cache as build)

      - name: Install dependencies
        run: pip install -r requirements.txt

      # TODO: Download build artifacts from build job

      - name: Run tests
        run: |
          pip install pytest
          pytest --junitxml=test-results.xml

      # TODO: Upload test results artifact

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          # TODO: Add pip caching

      - name: Install linter
        run: pip install ruff

      - name: Run lint
        run: ruff check app/
