# Solution 1: Basic Configuration
#
# This configuration provides a solid foundation for Go linting.
# Each section is documented to explain its purpose.

# Run configuration - controls how golangci-lint executes
run:
  # Timeout for the entire linting process
  # 5 minutes is generous for most projects
  timeout: 5m

  # Include test files in linting
  # Tests should follow the same quality standards
  tests: true

# Linter configuration - which linters to enable
linters:
  # Start with everything disabled for explicit control
  disable-all: true

  # Enable specific linters
  enable:
    # errcheck: Checks for unchecked errors
    # WHY: Unchecked errors are a common source of bugs.
    #      Go's error handling is explicit by design.
    - errcheck

    # govet: Reports suspicious constructs
    # WHY: Catches issues like printf format mismatches,
    #      struct tag issues, and other potential bugs.
    - govet

    # staticcheck: Advanced static analysis
    # WHY: Catches many issues that simpler tools miss,
    #      including deprecated API usage and inefficiencies.
    - staticcheck

    # unused: Finds unused code
    # WHY: Dead code adds maintenance burden and confusion.
    #      Keeping code clean helps maintainability.
    - unused
