# SOLUTION 3: Complete Deployment Pipeline

name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false  # Don't cancel in-progress deploys

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t myapp:${{ github.sha }} .

      - name: Save Docker image
        run: docker save myapp:${{ github.sha }} > image.tar

      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
          retention-days: 1

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load and test image
        run: |
          docker load < image.tar
          docker run --rm myapp:${{ github.sha }} python -c "print('Tests passed!')"

  # Deploy to staging (automatic)
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: staging
      url: https://staging.example.com

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load < image.tar

      - name: Deploy to staging
        env:
          DEPLOY_KEY: ${{ secrets.STAGING_DEPLOY_KEY }}
          ENVIRONMENT: staging
        run: |
          echo "Deploying to staging..."
          echo "Image: myapp:${{ github.sha }}"
          echo "Environment: $ENVIRONMENT"
          # Actual deployment commands would go here:
          # docker push $REGISTRY/myapp:${{ github.sha }}
          # kubectl set image deployment/myapp myapp=$REGISTRY/myapp:${{ github.sha }}

  # Smoke tests on staging
  smoke-test:
    name: Smoke Tests
    runs-on: ubuntu-latest
    needs: deploy-staging

    steps:
      - uses: actions/checkout@v4

      - name: Wait for deployment
        run: sleep 10  # Wait for service to be ready

      - name: Run smoke tests
        run: |
          echo "Running smoke tests against staging..."
          # Example smoke tests:
          # curl -f https://staging.example.com/health
          # curl -f https://staging.example.com/api/status
          echo "Smoke tests passed!"

      - name: Report results
        run: echo "Staging deployment verified successfully"

  # Deploy to production (requires approval)
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: smoke-test
    environment:
      name: production
      url: https://example.com

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load < image.tar

      - name: Deploy to production
        env:
          DEPLOY_KEY: ${{ secrets.PRODUCTION_DEPLOY_KEY }}
          ENVIRONMENT: production
        run: |
          echo "Deploying to production..."
          echo "Image: myapp:${{ github.sha }}"
          echo "Environment: $ENVIRONMENT"
          # Actual deployment commands would go here:
          # docker push $REGISTRY/myapp:${{ github.sha }}
          # kubectl set image deployment/myapp myapp=$REGISTRY/myapp:${{ github.sha }}

      - name: Verify deployment
        run: |
          echo "Verifying production deployment..."
          # curl -f https://example.com/health
          echo "Production deployment successful!"

      - name: Notify success
        run: |
          echo "Deployment complete!"
          echo "Version: ${{ github.sha }}"
          echo "Production URL: https://example.com"
