# SOLUTION 1: Multi-Language CI Pipeline

name: Multi-Language CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # Python tests with matrix
  python-test:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ['3.11', '3.12']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          cd backend
          pytest --cov --junitxml=test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: python-test-results-${{ matrix.os }}-${{ matrix.python }}
          path: backend/test-results.xml

  # Node.js tests with matrix
  node-test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: ['18', '20']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run tests
        run: |
          cd frontend
          npm test 2>&1 | tee test-output.txt || true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: node-test-results-${{ matrix.os }}-${{ matrix.node }}
          path: frontend/test-output.txt

  # Integration tests (run after both pass)
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [python-test, node-test]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run integration tests
        run: |
          echo "Running integration tests..."
          echo "Backend and frontend unit tests passed!"
          echo "Integration test complete."
