# golangci-lint configuration for this skill
# This serves as both the actual config and a teaching example

run:
  # Timeout for analysis
  timeout: 5m

  # Include test files
  tests: true

  # Skip generated files
  skip-dirs:
    - vendor
    - generated

  # Number of CPUs to use (0 = all available)
  concurrency: 0

# Linter configuration
linters:
  # Disable all linters first, then enable specific ones
  disable-all: true

  enable:
    # Bug Detection
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - staticcheck   # Advanced static analysis
    - unused        # Finds unused code

    # Style & Formatting
    - gofmt         # Checks formatting
    - goimports     # Checks import organization
    - gosimple      # Simplification suggestions

    # Code Quality
    - ineffassign   # Detects ineffectual assignments
    - typecheck     # Type checking

    # Best Practices
    - gocritic      # Opinionated linter with many checks
    - revive        # Replacement for golint

# Individual linter settings
linters-settings:
  errcheck:
    # Check type assertions
    check-type-assertions: true
    # Check blank identifiers
    check-blank: true

  govet:
    # Enable shadow checking
    shadow: true

  gofmt:
    # Simplify code
    simplify: true

  goimports:
    # Put local imports after 3rd party
    local-prefixes: github.com/labs-skills

  gocritic:
    # Enable additional checks
    enabled-tags:
      - diagnostic
      - style
      - performance

  revive:
    # Set severity
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: blank-imports
        severity: warning

# Issue reporting configuration
issues:
  # Don't limit number of issues per linter
  max-issues-per-linter: 0

  # Don't limit issues with same text
  max-same-issues: 0

  # Show all issues from a linter
  new: false

  # Exclude certain patterns
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - gocritic
        - errcheck

    # Exclude example files from some checks
    - path: examples/
      linters:
        - unused

# Output configuration
output:
  # Format: colored-line-number, line-number, json, tab, checkstyle
  formats:
    - format: colored-line-number

  # Print lines of code with issue
  print-issued-lines: true

  # Print linter name at end of issue
  print-linter-name: true

# Severity configuration
severity:
  # Default severity
  default-severity: warning

  # Rules for changing severity
  rules:
    - linters:
        - errcheck
      severity: error
    - linters:
        - govet
      severity: error
