# Example 3: Reusable Workflow Definition
# A reusable CI workflow that can be called from other repositories

name: Reusable Python CI

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.12'
        type: string

      runs-on:
        description: 'Runner to use'
        required: false
        default: 'ubuntu-latest'
        type: string

      run-lint:
        description: 'Whether to run linting'
        required: false
        default: true
        type: boolean

      run-security:
        description: 'Whether to run security scan'
        required: false
        default: true
        type: boolean

      coverage-threshold:
        description: 'Minimum coverage percentage'
        required: false
        default: '80'
        type: string

    secrets:
      CODECOV_TOKEN:
        description: 'Codecov upload token'
        required: false

    outputs:
      coverage:
        description: 'Test coverage percentage'
        value: ${{ jobs.test.outputs.coverage }}

jobs:
  lint:
    name: Lint
    runs-on: ${{ inputs.runs-on }}
    if: inputs.run-lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install linting tools
        run: pip install ruff mypy

      - name: Run Ruff
        run: ruff check .

      - name: Run Ruff format check
        run: ruff format --check .

  test:
    name: Test
    runs-on: ${{ inputs.runs-on }}
    needs: lint
    if: always() && (needs.lint.result == 'success' || needs.lint.result == 'skipped')

    outputs:
      coverage: ${{ steps.coverage.outputs.percentage }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest \
            --cov=src \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-fail-under=${{ inputs.coverage-threshold }}

      - name: Extract coverage percentage
        id: coverage
        run: |
          COVERAGE=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); print(f'{float(tree.getroot().attrib[\"line-rate\"]) * 100:.1f}')")
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT

      - name: Upload coverage to Codecov
        if: secrets.CODECOV_TOKEN
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: false

  security:
    name: Security Scan
    runs-on: ${{ inputs.runs-on }}
    if: inputs.run-security

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install security tools
        run: pip install bandit safety

      - name: Run Bandit
        run: bandit -r src/ -ll -q

      - name: Check dependencies
        run: safety check -r requirements.txt
        continue-on-error: true
