# Example 3: Lambda Event Handler
# A serverless function with multiple event triggers
# Demonstrates Lambda configuration patterns

name: image-processor
platform: lambda
description: Processes uploaded images and creates thumbnails

team: media-team
tags:
  environment: production
  cost-center: media-processing
  data-classification: internal

# Lambda compute configuration
compute:
  memory: 1024       # MB (128-10240)
  timeout: 60        # Seconds (1-900)
  runtime: python3.11

  # Architecture selection
  architecture: arm64  # arm64 for cost savings, x86_64 for compatibility

  # Concurrency controls
  reserved_concurrency: 100      # Max concurrent executions
  provisioned_concurrency: 5     # Pre-warmed instances for low latency

# Lambda layers for shared code/dependencies
layers:
  - arn:aws:lambda:us-east-1:123456789:layer:pillow:3
  - arn:aws:lambda:us-east-1:123456789:layer:common-utils:1

# Event triggers - multiple sources
triggers:
  # S3 trigger for JPG uploads
  - type: s3
    bucket: user-uploads
    events:
      - s3:ObjectCreated:*
    filter:
      prefix: images/
      suffix: .jpg

  # S3 trigger for PNG uploads
  - type: s3
    bucket: user-uploads
    events:
      - s3:ObjectCreated:*
    filter:
      prefix: images/
      suffix: .png

  # API Gateway trigger for manual processing
  - type: api_gateway
    path: /process
    method: POST
    authorization: AWS_IAM

  # SQS trigger for batch processing
  - type: sqs
    queue_arn: arn:aws:sqs:us-east-1:123456789:image-processing-queue
    batch_size: 10
    batch_window: 5

# VPC configuration for private resource access
vpc:
  security_group_ids:
    - sg-12345678
  subnet_ids:
    - subnet-abcd1234
    - subnet-efgh5678

# Environment variables
environment:
  OUTPUT_BUCKET: processed-images
  THUMBNAIL_SIZE: "200x200"
  JPEG_QUALITY: "85"
  LOG_LEVEL: info
  POWERTOOLS_SERVICE_NAME: image-processor
  POWERTOOLS_METRICS_NAMESPACE: MediaProcessing

# Dead letter queue for failed invocations
dead_letter:
  target_arn: arn:aws:sqs:us-east-1:123456789:image-processor-dlq
