# Example 2: S3 and SQS Dependencies
# A file processing service with S3 buckets and SQS queues
# Demonstrates storage and messaging patterns

name: document-processor
platform: lambda
description: Processes uploaded documents, extracts metadata, generates thumbnails

team: document-team
tags:
  environment: production
  tier: processing
  data-classification: confidential

compute:
  memory: 2048
  timeout: 300
  runtime: python3.11
  architecture: arm64

triggers:
  - type: sqs
    queue_arn: arn:aws:sqs:us-east-1:123456789012:document-processing-queue
    batch_size: 5

# S3 and SQS dependencies
dependencies:
  # Source bucket - read uploaded documents
  - type: aws_s3_bucket
    name: document-uploads
    mode: read
    prefix: incoming/
    # Server-side encryption with customer KMS key
    encryption:
      enabled: true
      kms_key: ${kms:documents-key}

  # Processed documents bucket - write results
  - type: aws_s3_bucket
    name: document-processed
    mode: write
    prefix: processed/
    encryption:
      enabled: true
      kms_key: ${kms:documents-key}
    # Lifecycle rules configured at bucket level
    lifecycle:
      - transition_to_ia: 30        # Move to IA after 30 days
      - transition_to_glacier: 90   # Move to Glacier after 90 days

  # Thumbnails bucket - write generated thumbnails
  - type: aws_s3_bucket
    name: document-thumbnails
    mode: write
    prefix: thumbnails/
    # Public read for CDN delivery
    public_read: true

  # Processing queue - receive jobs
  - type: aws_sqs_queue
    name: document-processing-queue
    mode: consumer
    batch_size: 5
    visibility_timeout: 360  # Longer than Lambda timeout
    wait_time_seconds: 20    # Long polling

  # Notification queue - send completion events
  - type: aws_sqs_queue
    name: document-notifications
    mode: producer

  # Dead letter queue - failed message handling
  - type: aws_sqs_queue
    name: document-processing-dlq
    mode: producer

  # Metadata storage
  - type: aws_dynamodb_table
    name: document-metadata
    mode: write

dead_letter:
  target_arn: arn:aws:sqs:us-east-1:123456789012:document-processing-dlq

environment:
  SOURCE_BUCKET: document-uploads
  OUTPUT_BUCKET: document-processed
  THUMBNAIL_BUCKET: document-thumbnails
  NOTIFICATION_QUEUE: ${sqs:document-notifications:url}
  METADATA_TABLE: document-metadata
  LOG_LEVEL: info
